name: Make Build Check

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    name: Run Make
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        # submodules オプションを削除

      - name: Install build tools and dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential libx11-dev libxext-dev zlib1g-dev

      - name: Clone MiniLibX
        run: |
          rm -rf minilibx-linux
          git clone https://github.com/42Paris/minilibx-linux.git minilibx-linux

      - name: Build MiniLibX
        run: |
          cd minilibx-linux
          make

      - name: Run make
        run: make