name: Make Build Check

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    name: Run Make
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        # submodules オプションを削除

      - name: Run make
        run: make