name: Make Build Check

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    name: Run Make
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        # submodules オプションを削除

      # グラフィック関連のライブラリをインストール
      - name: Install graphic library
        run: |
          sudo apt-get update
          sudo apt-get install -y libx11-dev libxext-dev libbsd-dev

      - name: Run make
        run: make